name: Package with PyInstaller - Windows

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Install PyInstaller
      run: pip install pyinstaller
    - name: Build with PyInstaller
      run: pyinstaller nndownload.spec
    - uses: actions/upload-artifact@v4
      with:
        name: nndownload
        path: dist/