name: Package with PyInstaller - Windows

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
      with:
        path: src
        spec: nndownload.spec
        requirements: requirements.txt
    - uses: actions/upload-artifact@v2
      with:
        name: nndownload
        path: src/dist/windows